services:
  - type: web
    name: near-intents-swap-api
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    plan: starter
    numInstances: 1
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health